In [1]:
import pandas

In [2]:
import matplotlib.pyplot as plt

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM,Input
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from keras.models import Model
import math

Using TensorFlow backend.


In [4]:
import numpy as np

In [5]:
np.random.seed(7)

In [6]:
dataset = pandas.read_csv('Downloads/international-airline-passengers.csv',usecols=[1],engine='python',skipfooter=3)

In [7]:
dataset = dataset.values

In [8]:
dataset = dataset.astype('float32')

In [9]:
scaler = MinMaxScaler(feature_range=(0,1))

In [10]:
dataset = scaler.fit_transform(dataset)

In [11]:
train_size = int(len(dataset) * 0.67)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))

(96, 48)


In [12]:
def create_dataset(dataset,look_back = 3):
    dataX = []
    dataY = []
    for i in xrange(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back),0]
        dataX.append(a)
        dataY.append(dataset[i+look_back,0])
    return np.asarray(dataX),np.asarray(dataY)

In [13]:
look_back = 3
trainX,trainY = create_dataset(train,look_back)
testX,testY = create_dataset(test,look_back)

In [14]:
trainX = np.reshape(trainX,(trainX.shape[0],1,trainX.shape[1]))
testX = np.reshape(testX,(testX.shape[0],1,testX.shape[1]))

In [15]:
input_data = Input(shape = (1,look_back))

In [16]:
x = LSTM(4)(input_data)

In [17]:
x = Dense(1)(x)

In [18]:
output = x

In [19]:
model = Model(input_data,output)

In [20]:
model.compile(loss = 'mean_squared_error',optimizer='adam')

In [21]:
model.fit(trainX,trainY,epochs = 100,batch_size=1,verbose = 2)

Epoch 1/100
3s - loss: 0.0542
Epoch 2/100
0s - loss: 0.0258
Epoch 3/100
0s - loss: 0.0167
Epoch 4/100
0s - loss: 0.0145
Epoch 5/100
0s - loss: 0.0129
Epoch 6/100
0s - loss: 0.0116
Epoch 7/100
0s - loss: 0.0105
Epoch 8/100
0s - loss: 0.0094
Epoch 9/100
0s - loss: 0.0081
Epoch 10/100
0s - loss: 0.0074
Epoch 11/100
0s - loss: 0.0066
Epoch 12/100
0s - loss: 0.0060
Epoch 13/100
0s - loss: 0.0056
Epoch 14/100
0s - loss: 0.0052
Epoch 15/100
0s - loss: 0.0050
Epoch 16/100
0s - loss: 0.0049
Epoch 17/100
0s - loss: 0.0046
Epoch 18/100
0s - loss: 0.0045
Epoch 19/100
0s - loss: 0.0045
Epoch 20/100
0s - loss: 0.0043
Epoch 21/100
0s - loss: 0.0043
Epoch 22/100
0s - loss: 0.0042
Epoch 23/100
0s - loss: 0.0042
Epoch 24/100
0s - loss: 0.0042
Epoch 25/100
0s - loss: 0.0040
Epoch 26/100
0s - loss: 0.0041
Epoch 27/100
0s - loss: 0.0040
Epoch 28/100
0s - loss: 0.0040
Epoch 29/100
0s - loss: 0.0039
Epoch 30/100
0s - loss: 0.0038
Epoch 31/100
0s - loss: 0.0038
Epoch 32/100
0s - loss: 0.0037
Epoch 33/100
0s -

In [22]:
print trainX

[[[ 0.01544401  0.02702703  0.05405405]]

 [[ 0.02702703  0.05405405  0.04826255]]

 [[ 0.05405405  0.04826255  0.03281853]]

 [[ 0.04826255  0.03281853  0.05984557]]

 [[ 0.03281853  0.05984557  0.08494207]]

 [[ 0.05984557  0.08494207  0.08494207]]

 [[ 0.08494207  0.08494207  0.06177607]]

 [[ 0.08494207  0.06177607  0.02895753]]

 [[ 0.06177607  0.02895753  0.        ]]

 [[ 0.02895753  0.          0.02702703]]

 [[ 0.          0.02702703  0.02123553]]

 [[ 0.02702703  0.02123553  0.04247104]]

 [[ 0.02123553  0.04247104  0.07142857]]

 [[ 0.04247104  0.07142857  0.05984557]]

 [[ 0.07142857  0.05984557  0.04054055]]

 [[ 0.05984557  0.04054055  0.08687258]]

 [[ 0.04054055  0.08687258  0.12741312]]

 [[ 0.08687258  0.12741312  0.12741312]]

 [[ 0.12741312  0.12741312  0.10424709]]

 [[ 0.12741312  0.10424709  0.05598456]]

 [[ 0.10424709  0.05598456  0.01930502]]

 [[ 0.05598456  0.01930502  0.06949806]]

 [[ 0.01930502  0.06949806  0.07915059]]

 [[ 0.06949806  0.07915059  0.0888