In [1]:
import pandas
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM,Input
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from keras.models import Model
import math
import numpy as np

Using TensorFlow backend.


In [2]:
np.random.seed(7)
dataset = pandas.read_csv('Downloads/international-airline-passengers.csv',usecols=[1],engine='python',skipfooter=3)
dataset = dataset.values
dataset = dataset.astype('float32')
scaler = MinMaxScaler(feature_range=(0,1))
dataset = scaler.fit_transform(dataset)
train_size = int(len(dataset) * 0.67)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))

(96, 48)


In [3]:
def create_dataset(dataset,look_back = 3):
    dataX = []
    dataY = []
    for i in xrange(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back),0]
        dataX.append(a)
        dataY.append(dataset[i+look_back,0])
    return np.asarray(dataX),np.asarray(dataY)


In [4]:
look_back = 3
trainX,trainY = create_dataset(train,look_back)
testX,testY = create_dataset(test,look_back)
trainX = np.reshape(trainX,(trainX.shape[0],trainX.shape[1],1))
testX = np.reshape(testX,(testX.shape[0],testX.shape[1],1))
print trainX
print np.shape(trainX)
input_data = Input(shape = (look_back,1))
x = LSTM(4)(input_data)
x = Dense(1)(x)
output = x
model = Model(input_data,output)
model.compile(loss = 'mean_squared_error',optimizer='adam')
model.fit(trainX,trainY,epochs = 100,batch_size=1,verbose = 2)

[[[ 0.01544401]
  [ 0.02702703]
  [ 0.05405405]]

 [[ 0.02702703]
  [ 0.05405405]
  [ 0.04826255]]

 [[ 0.05405405]
  [ 0.04826255]
  [ 0.03281853]]

 [[ 0.04826255]
  [ 0.03281853]
  [ 0.05984557]]

 [[ 0.03281853]
  [ 0.05984557]
  [ 0.08494207]]

 [[ 0.05984557]
  [ 0.08494207]
  [ 0.08494207]]

 [[ 0.08494207]
  [ 0.08494207]
  [ 0.06177607]]

 [[ 0.08494207]
  [ 0.06177607]
  [ 0.02895753]]

 [[ 0.06177607]
  [ 0.02895753]
  [ 0.        ]]

 [[ 0.02895753]
  [ 0.        ]
  [ 0.02702703]]

 [[ 0.        ]
  [ 0.02702703]
  [ 0.02123553]]

 [[ 0.02702703]
  [ 0.02123553]
  [ 0.04247104]]

 [[ 0.02123553]
  [ 0.04247104]
  [ 0.07142857]]

 [[ 0.04247104]
  [ 0.07142857]
  [ 0.05984557]]

 [[ 0.07142857]
  [ 0.05984557]
  [ 0.04054055]]

 [[ 0.05984557]
  [ 0.04054055]
  [ 0.08687258]]

 [[ 0.04054055]
  [ 0.08687258]
  [ 0.12741312]]

 [[ 0.08687258]
  [ 0.12741312]
  [ 0.12741312]]

 [[ 0.12741312]
  [ 0.12741312]
  [ 0.10424709]]

 [[ 0.12741312]
  [ 0.10424709]
  [ 0.05598456]]

